// SPDX-FileCopyrightText: 2026 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "mongoose/mongoose_glue.h"

int main(void) {
  mongoose_init();

  for (;;) {
    mongoose_poll();
  }

  return 0;
}
